title:  "Geppa Dev-Diary"
tagline: "diary using github"
description:

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Interesting Facts', folder: 'pages', file: 'facts.html'}
- {name: 'Learning Resources', folder: 'pages', file: '개발일지.html'}
- {name: 'Sample Posts', folder: 'pages', file: 'sample-posts.html'}
- {name: 'Documentation', folder: 'pages', file: 'documentation.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/'}
- {icon: 'facebook', link: 'https://www.facebook.com/geppa04'}
- {icon: 'instagram', link: 'https://instagram.com/geppa_min'}
- {icon: 'envelope', link: 'mailto:asdjklfgh97@naver.com'}
- {icon: 'rss-square', link: 'feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
